### ISSUE TITLE
link and the picture of the product

### ISSUE THREAD

**Issue by Amilcar34** [5kilian/ebay-api#1]
Hi. Can I get or capture the link and the picture of the product with your api? If this can be pausible, how can I do this?

**Comment by 5kilian** [comment]
It is not possible now, but I'll implement it for you.

**Comment by Amilcar34** [comment]
I thought it was an api of another type, I started it and being in debug mode I understood how it worked and adding 10 lines of code in that project I was able to get what I needed.
I congratulate you on the idea, it's great.

**Comment by 5kilian** [comment]
I've added the requested features. Thanks for the support.
